/* ============================================
; Title:  enhanced composer list
; Author: Professor Krasso
; Date:   14 January 2021
; Modified by: Wendy Leon
  Edited: 21 January 2021
; Description: app module
;===========================================
*/
// external files files being imported
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { ContactUsComponent } from './contact-us/contact-us.component';
import { ComposerListComponent } from './composer-list/composer-list.component';
import { AboutComponent } from './about/about.component';
import { ComposerDetailsComponent } from './composer-details/composer-details.component';
import { RouterModule } from '@angular/router'
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

//cli declarations autogenerated when creating each component
@NgModule({
  declarations: [
    AppComponent,
    ContactUsComponent,
    ComposerListComponent,
    AboutComponent,
    ComposerDetailsComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    RouterModule,
    FormsModule,
    ReactiveFormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

